language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - ruby-head
  - rbx
matrix:
  include:
  - rvm: jruby-19mode
    jdk: oraclejdk7
  - rvm: jruby-19mode
    jdk: openjdk7
before_install:
  - gem update --system
  - gem --version
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq zip unzip
  - echo `whereis zip`
  - echo `whereis unzip`
allow_failures:
  - rvm: ruby-head
